"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 07:38:55.606542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_donations_email'), 'money_donations', ['email'], unique=False)
    op.create_index(op.f('ix_money_donations_id'), 'money_donations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('donor', 'recipient', 'officer', 'admin', name='user_role'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='user_status'), nullable=False),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_index(op.f('ix_escalations_raised_by'), 'escalations', ['raised_by'], unique=False)
    op.create_table('food_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('available', 'requested', 'accepted', 'reserved', 'picked_up', 'completed', 'cancelled', name='listing_status'), nullable=False),
    sa.Column('accepted_by', sa.String(length=255), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), server_default='pending_review', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_listings_donor_id'), 'food_listings', ['donor_id'], unique=False)
    op.create_index(op.f('ix_food_listings_id'), 'food_listings', ['id'], unique=False)
    op.create_table('food_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=False),
    sa.Column('needed_by', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'quality_checked', 'delivering', 'delivered', 'picked_up', 'cancelled', name='request_status'), nullable=False),
    sa.Column('accepted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['food_listings.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_requests_id'), 'food_requests', ['id'], unique=False)
    op.create_index(op.f('ix_food_requests_listing_id'), 'food_requests', ['listing_id'], unique=False)
    op.create_index(op.f('ix_food_requests_recipient_id'), 'food_requests', ['recipient_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('feedback_status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['food_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_recipient_id'), 'feedback', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_feedback_request_id'), 'feedback', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_request_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_recipient_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_food_requests_recipient_id'), table_name='food_requests')
    op.drop_index(op.f('ix_food_requests_listing_id'), table_name='food_requests')
    op.drop_index(op.f('ix_food_requests_id'), table_name='food_requests')
    op.drop_table('food_requests')
    op.drop_index(op.f('ix_food_listings_id'), table_name='food_listings')
    op.drop_index(op.f('ix_food_listings_donor_id'), table_name='food_listings')
    op.drop_table('food_listings')
    op.drop_index(op.f('ix_escalations_raised_by'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_money_donations_id'), table_name='money_donations')
    op.drop_index(op.f('ix_money_donations_email'), table_name='money_donations')
    op.drop_table('money_donations')
    # ### end Alembic commands ###