"""community events

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 09:01:24.080496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_subscribers_email'), 'event_subscribers', ['email'], unique=True)
    op.create_table('community_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_events_id'), 'community_events', ['id'], unique=False)
    op.create_index(op.f('ix_community_events_starts_at'), 'community_events', ['starts_at'], unique=False)
    op.create_table('event_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['community_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_signup')
    )
    op.create_index(op.f('ix_event_signups_event_id'), 'event_signups', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_signups_user_id'), 'event_signups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_signups_user_id'), table_name='event_signups')
    op.drop_index(op.f('ix_event_signups_event_id'), table_name='event_signups')
    op.drop_table('event_signups')
    op.drop_index(op.f('ix_community_events_starts_at'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_id'), table_name='community_events')
    op.drop_table('community_events')
    op.drop_index(op.f('ix_event_subscribers_email'), table_name='event_subscribers')
    op.drop_table('event_subscribers')
    # ### end Alembic commands ###