"""payment tracking

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 09:13:59.594574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_donations', sa.Column('source', sa.String(length=20), server_default='manual', nullable=False))
    op.add_column('money_donations', sa.Column('payment_ref', sa.String(length=64), nullable=True))
    op.alter_column('money_donations', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.create_unique_constraint('uq_money_donations_payment_ref', 'money_donations', ['payment_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_money_donations_payment_ref', 'money_donations', type_='unique')
    op.execute("UPDATE money_donations SET card_last4 = '0000' WHERE card_last4 IS NULL")
    op.alter_column('money_donations', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.drop_column('money_donations', 'payment_ref')
    op.drop_column('money_donations', 'source')
    # ### end Alembic commands ###